### ISSUE TITLE
Need a Login Component

### ISSUE THREAD

**Issue by avinasdube** [avinasdube/shareanalytics#10]
### 🏴󠁧󠁢󠁷󠁬󠁳󠁿 **ISSUE** :

> We need a beautiful login component to let our users log in to our platform. The UI design for required login component is given below. Some changes need to be done in Login component UI design before finalizing it. 

**- Following are the changes should be addressed while developing it :** 

1. Remove the title "Welcome back" with "Login to Share Analytics".
2. Put the logo of app (stored in sa-client/src/assets/icons/) beside left of the title.
3. Background should be white.
4. Do not include 'Back to Home'.
5. Use color code defined as variables in ``sa-client/src/components/organisms/Navbar/Navbar.scss``

![image](https://github.com/avinasdube/shareanalytics/assets/85872996/cdefd7ce-44bb-4ca5-85ef-ab80aa12a71c)

**Comment by Sky-De** [comment]
@avinasdube hi, i would like to work on this, please assign this to me

**Comment by avinasdube** [comment]
@Sky-De ! We don't have a ``CONTRIBUTING.md`` guide by now in our repo. You'll have to figure out running the app in your local machine on your own.
