### ISSUE TITLE
#15 refactore routing

### ISSUE THREAD

**Issue by Sky-De** [avinasdube/shareanalytics#14]
**Issue A**:  
because of no standard routing , we do not have access to laylout in all entire app and diffrent routes

browser:
![222222222222222222](https://github.com/avinasdube/shareanalytics/assets/79264045/945f2ad7-bd39-4400-a7bc-f684bbd764a3)

code:
![333333333333](https://github.com/avinasdube/shareanalytics/assets/79264045/07299069-6809-4913-af95-f0db707b7445)

**Task A**:  refactore roteing with standard approach 

*********************************************************************************************************************************************

**Issue B**: signin btn and logo do not have any link or navigation, we must reach signIn route using url now

Brower
![11111](https://github.com/avinasdube/shareanalytics/assets/79264045/59c4f6ac-26ff-4360-b635-ce4f58932632)

**Task B**: add functionality to logo and signin btn

**Comment by Sky-De** [comment]
@avinasdube please assign this to me
after PR and merge mark this issue as done 
thanks

**Comment by avinasdube** [comment]
Thanks for raising your issue ! As far as you can see, we just started this project. So no major achievements met by now.

- Regarding Your Issue A : (' we do not have access to laylout in all entire app and diffrent routes')
  
The existing defined routing structure do meet out goals. Regarding Layout definition, we don't need 'Navbar' & 'Footer' on signup/login pages. In fact, we'll use two popup components for signup/login on clicking Login button on Navbar.

- Regarding Your Issue B : ('signin btn and logo do not have any link or navigation, we must reach signIn route using url now')

Yes ! Signin and logo buttons are not functional now. But once signup/login components are complete, we'll make the Login button functional.

If you still think I'm not getting what you're trying to point out, then push your changes with a fresh new PR. We'll look into it and further notify you.

**Comment by Sky-De** [comment]
@avinasdube  thanks for clerify, i did not know you will use pop up,  by the way i fixed that before creating issue, and already sended PR
for now i think it is better practice and cleaner and more understandable source code for up coming contributions
thanks

**Comment by avinasdube** [comment]
If you want to contribute more then do check new issues when created. We'd love your contribution.
