### ISSUE TITLE
Making Login Button Functional (Feature) 

### ISSUE THREAD

**Issue by avinasdube** [avinasdube/shareanalytics#18]
## Description

**Feature Description:**

I'd like to request a new feature that enhances the user experience on our website. Currently, we have a login button on the navbar, but it's not yet functional. I propose adding functionality to this button so that when users click it, a pop-up login form appears, allowing them to log in without navigating away from the current page.

## Use Case

**Use Case:**

This feature would greatly improve user convenience. Users often want to access their accounts quickly without leaving the page they're on. By having a pop-up login form triggered by the navbar button, we can provide a seamless and efficient login experience.

## Proposed Solution

**Suggest a Solution:**

- I suggest implementing the following solution:

1. When a user clicks the "Login" button in the navbar, a beautiful pop-up window appears over the current page.

2. The pop-up should use login form located in path ``sa-client/src/components/pages/login/``.

3. Users can enter their login credentials and submit the form without leaving the current page.

4. On clicking the login button of navbar, the recommended login component should appear aligned at center of the current homepage screen with a popup effect.

5. Also, provide a close button on login component on right top side parallel to app logo, to close the currently opened login form if a user wants it to close.

```bash
Note : Avoid changing unassigned codes/files. Also, do not change the existing UI design of referenced login 
component except adding a new close button to it.
```

## Alternatives

**Alternatives Considered:**

Sorry, no alternatives suggested.

## Additional Context

**Additional Context:**

Adding this feature would align with our goal of providing a user-friendly and efficient platform. It would enhance the overall user experience and make it easier for users to access their accounts and interact with our website.

**Related Screenshots**

Use below screenshot as referenced suggestion for required feature. 

![image](https://github.com/avinasdube/shareanalytics/assets/85872996/efa2e577-ab2b-4023-a750-13325a100286)

## Checklist

- [x] I have searched for similar feature requests before creating this one.
- [x] I have provided a clear and concise description of the feature.
- [x] I have described the use case or scenario.
- [x] I have considered and mentioned any alternatives.

**Comment by deeksharungta** [comment]
@avinasdube I want to work on this issue. Could you please consider assigning it to me.

**Comment by avinasdube** [comment]
Assigned to you. Keep up with **issue guidelines**. Happy contributing ! 👍
