### ISSUE TITLE
New Signup Component with Pop-Up Effect (Feature)

### ISSUE THREAD

**Issue by avinasdube** [avinasdube/shareanalytics#19]
## Description

**Feature Description:**

Currently, we have a "Signup" button, but it is not functional. I suggest adding a new signup component that opens in a pop-up window when users click the "Signup" button, creating a more user-friendly and streamlined registration process.

## Use Case

**Use Case:**

This feature would significantly improve the user experience for new users. It allows them to initiate the signup process without leaving their current context. By having a pop-up signup component, we make registration more convenient and reduce the friction associated with navigating to a separate page.

## Proposed Solution

**Suggest a Solution:**

- Here's the proposed solution:

1. When a user clicks the "Signup" button, a beautiful pop-up window appears over the current page.

2. The pop-up should open a signup form same as login form located in ``sa-client/src/components/pages/login/`` but with an extra input field 'Confirm Password' before submitting the form. 

3. Users can fill out the form directly within the pop-up, making the registration process quick and efficient.

4. Upon successful registration, users receive a confirmation message, and then directed to the same login form mentioned above. In case of an error, a helpful error message is displayed.

## Alternatives

**Alternatives Considered:**

No alternatives suggested.

## Additional Context

**Additional Context:**

Adding this feature would align with our goal of providing a user-friendly and efficient platform. It would enhance the overall user experience and make it easier for users to access their accounts and interact with our website.

**Related Screenshots**

Use below screenshot as referenced suggestion for required signup form.

![image](https://github.com/avinasdube/shareanalytics/assets/85872996/8a4f7d43-7323-4fda-b933-47e0cfc48466)

## Checklist

- [x] I have searched for similar feature requests before creating this one.
- [x] I have provided a clear and concise description of the feature.
- [x] I have described the use case or scenario.
- [x] I have considered and mentioned any alternatives.

**Comment by navdeep1840** [comment]
@avinasdube I want to contribute to your repo. Can you assign this task to me?

**Comment by avinasdube** [comment]
Assigned to you. Keep up with **issue guidelines**. Happy contributing.
**Note :** For better context, you can check preview in pull request #21 by Deeksha.

**Comment by avinasdube** [comment]
@navdeep1840 are you really doing it ??

**Comment by navdeep1840** [comment]
@avinasdube  I am on it .
