### ISSUE TITLE
Help needed to deploy server on Vercel

### ISSUE THREAD

**Issue by avinasdube** [avinasdube/shareanalytics#28]
**Description :**

The frontend of this application has been successfully deployed on Vercel. Now we want to deploy the server too, so that the app becomes fully functional. I've tried deploying it but not succeeded. It displays "Failed to load resource: the server responded with a status of 404 ()" error everytime. So if anyone can help me deploying the server will be much appreciated.

**Comment by VishruthVS** [comment]
Let's work on it

**Comment by evoxf1** [comment]
whats the issue, is it closed or still open

**Comment by avinasdube** [comment]
> whats the issue, is it closed or still open

issue is the server-side of this project is expected to be deployed on vercel but due to unexpected errors, everytime i'm trying to deploy it fails. hence, want someone's help who knows how to deploy server on vercel for such mern projects.
